# Site settings
title: "make all"
description: > 
  Write a description of your website here.

author: Son Geon(jen6)
email: kde.jen6@gmail.com
twitter_username: 
github_username: jen6

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jen6.github.io" # the base hostname & protocol for your site
excerpt_seperator:  <!--break-->

google_analytics_id: UA-140782418-1
disqus_id: "makeall-jen6"

# Build settings
include: [_pages, _move]
markdown: kramdown
permalink: /:year/:month/:title.html

kramdown:
  input: GFM
  syntax_hightlighter: rouge
sass:
    style: compressed

exclude: [vendor]

# deployment
host: 0.0.0.0
port: 5000
